services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d mydb']
      interval: 5s
      timeout: 5s
      retries: 5
  pgweb:
    image: sosedoff/pgweb
    ports:
      - '8081:8081'
    environment:
      PGWEB_DATABASE_URL: postgres://admin:secret@postgres:5432/mydb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
